### PR TITLE
Added an option for binary export/import using Kryo

### PR DESCRIPTION
**Pull request by Sahasrara**
I was having trouble exporting our database to graphML format because:
- it contained null characters
- it couldn't handle nodes with lists as properties
- it couldn't handle domain objects with the same field names, but different types

I added support for exporting/importing neo4j data as binary data.

### CODE REVIEW

**Comment by Sahasrara** [comment]
Please let me know if you want modifications, or if you don't want these features at all

**Comment by jexp** [comment]
Hi Eric,

thanks a lot for this! Sorry, I missed the email-notification for your PR, and only saw it now. :(

I meant to add support for a binary format too, actually I wanted to use Neo4j's 3.0 packstream format.
Going format, I also want to add all these importers and exporters to APOC, there I wanted to start with Packstream. Do you know how big the Kryo dependency is (incl. transitives)?

Btw. I also would love to fix the GraphML export, so if you have time to help me to root out the issues there, that would be really helpful.

Some notes for this PR:
- can you please squash your commits into one
- can you remove all the files from the PR, where your IDE just changed imports or formatting or similar things, currently it has 40 changed files, while it should be at most 4-6 or so

**Comment by Sahasrara** [comment]
Oh, I didn't know about packstream.  I just used Kryo because I was familiar with it from Apache Storm.  I don't think it would be terribly difficult to swap out Kryo for something else in the future.

Total size (kryo, objenesis, minlog):  332.7kB
I'll create (modify if possible) a new pull request with squashed commits and send it along (sans import optimization) so you can check it out.

Sure, I can take a look at the graphml stuff when I've got a little more time on my hands.

**Comment by jexp** [comment]
Thanks a lot !

**Pull request closed without merging**
